# 영상 컨볼루션
> dst = cv2.filter2D(src, ddepth, kernel, dst, anchor, delta, borderType) <br>
src: 입력 영상, Numpy 배열 <br>
ddepth: 출력 영상의 dtype (-1: 입력 영상과 동일) <br>
kernel: 컨볼루션 커널, float32의 n x n 크기 배열 <br>
dst(optional): 결과 영상 <br>
anchor(optional): 커널의 기준점, default: 중심점 (-1, -1) <br>
delta(optional): 필터가 적용된 결과에 추가할 값 <br>
borderType(optional): 외곽 픽셀 보정 방법 지정 <br>

In [43]:
import cv2
import numpy as np
import random
import tensorflow as tf

# 레나 영상 불러오기
src = cv2.imread('./image/lena.jpg')


# 3x3 필터 생성
filter1 = np.random.randint(0, 2, size=(3,3))
print(filter1)

dst = cv2.filter2D(src,-1, kernel=filter1)
dst2 = cv2.filter2D(dst,-1, kernel=filter1)
dst3 = cv2.filter2D(dst2,-1, kernel=filter1)

dst4 = tf.nn.conv2d(src, filter1, 2,"SAME")
# print(type(src))



cv2.imshow('dst', dst)
cv2.imshow('dst2', dst2)
cv2.imshow('dst3', dst3)
# cv2.imshow('dst4', dst4)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[0 1 1]
 [1 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


-1